import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "@/assets/css/globals.css";
import "@/assets/css/side-menu/side-menu.css";
import "@/assets/css/header/header.css";
import "@/assets/css/stat-card/stat-card.css";
import "@/assets/css/home/home.css";

import Header from "@/components/global/Header";
import SideMenu from "@/components/global/SideMenu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "BiLL HUB",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ display: "flex" }}
      >
        <div>
          <SideMenu />
        </div>
        <div>
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
